let questions = [
  {question: "What is the supreme law of the land?",
  answer:"The Consitution"},
  {question: "What does the Constitution do?",
  answer:"Sets up the government, defines the government, protects basic rights of Americans"},
  {question: "The idea of self-government is in the first three words of the Constitution. What are these words?",
  answer:"We the People"},
  {question: "What is an amendment?",
  answer:"A change (to the Constitution), an addition (to the Constitution)"},
  {question: "What do we call the first ten amendments to the Constitution?",
  answer:"The Bill of Rights"},
  {question: "What is one right or freedom from the First Amendment?",
  answer:"Speech, religion, assembly, press, petition, the government"},
  {question: "How many amendments does the Constitution have?",
  answer:"Twenty-seven (27)"},
  {question: "What did the Declaration of Independence do?",
  answer:"Announced our independence (from Great Britain), declared our independence (from Great Britain), said that the United States is free (from Great Britain)"},
  {question: "What are two rights in the Declaration of Independence?",
  answer:"Life, liberty, pursuit of happiness"},
  {question: "What is freedom of religion?",
  answer:"You can practice any religion, or not practice a religion."},
  {question: " What is the economic system in the United States?",
  answer:"Capitalist, Economy market economy"},
  {question: "What is the “rule of law”?",
  answer:"Everyone must follow the law. Leaders must obey the law. Government must obey the law. No one is above the law."},
  {question: "Name one branch or part of the government.",
  answer:"Congress, Legislative, President, Executive, The Courts, Judicial"},
  {question: "What stops one branch of government from becoming too powerful?",
  answer:"Checks and balances, Separation of powers"},
  {question: "Who is in charge of the executive branch?",
  answer:"The President"},
  {question: "Who makes federal laws?",
  answer:"Congress Senate and House (of Representatives) (U.S. or national) legislature"},
  {question: "What are the two parts of the U.S. Congress?",
  answer:"the Senate and House (of Representatives)"},
  {question: "How many U.S. Senators are there?",
  answer:"100"},
  {question: "We elect a U.S. Senator for how many years?",
  answer:"6 Years"},
  {question: "Who is one of your state’s U.S. Senators now?",
  answer:"Alex Padilla"},
  {question: "The House of Representatives has how many voting members?",
  answer:"Four Hundred Thirty-Five (435)"},
  {question: "We elect a U.S. Representative for how many years?",
  answer:"Two 2"},
  {question: "Name your U.S. Representative.",
  answer:"Young Kim"},
  {question: "Who does a U.S. Senator represent?",
  answer:"All people of the State"},
  {question: "Why do some states have more Representatives than other states?",
  answer:"Because some states have more people"},
  {question: "We elect a President for how many years?",
  answer:"Four 4"},
  {question: "In what month do we vote for President?",
  answer:"November"},
  {question: " What is the name of the President of the United States now?",
  answer:"Joe Biden"},
  {question: "What is the name of the Vice President of the United States now?",
  answer:"Kamala Harris"},
  {question: "If the President can no longer serve, who becomes President?",
  answer:"the Vice President"},
  {question: "If both the President and the Vice President can no longer serve, who becomes President?",
  answer:"the Speaker of the House"},
  {question: "Who is the Commander in Chief of the military?",
  answer:"the President"},
  {question: "Who signs bills to become laws?",
  answer:"the President"},
  {question: "Who vetoes bills?",
  answer:"the President"},
  {question: "What does the President’s Cabinet do?",
  answer:"advises the President"},
  {question: "What are two Cabinet-level positions?",
  answer:"Secretary of Education, Vice President"},
  {question: "What does the judicial branch do?",
  answer:"reviews laws explains laws resolves disputes (disagreements) decides if a law goes against the Constitution"},
  {question: "What is the highest court in the United States?",
  answer:"the Supreme Court"},
  {question: "How many justices are on the Supreme Court?",
  answer:"9"},
  {question: "Who is the Chief Justice of the United States now",
  answer:"John Roberts"},
  {question: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
  answer:"to print money"},
  {question: "Under our Constitution, some powers belong to the states. What is one power of the states?",
  answer:"provide schooling and education"},
  {question: "Who is the Governor of your state now?",
  answer:"Gavin Newsom"},
  {question: "What is the capital of your state?",
  answer:"Sacramento"},
  {question: "What are the two major political parties in the United States?",
  answer:"Democratic and Republican"},
  {question: "What is the political party of the President now?",
  answer:"Democratic Party"},
  {question: "What is the name of the Speaker of the House of Representatives now?",
  answer:"Nancy Pelosi"},
  {question: "There are four amendments to the Constitution about who can vote. Describe one of them.",
  answer:"Any citizen can vote. (Women and men can vote.)"},
  {question: "What is one responsibility that is only for United States citizens?*",
  answer:"vote in a federal election"},
  {question: "Name one right only for United States citizens?",
  answer:"vote in a federal election"},
  {question: "What are two rights of everyone living in the United States?",
  answer:"freedom of speech freedom of assembly freedom of religion"},
  {question: "What do we show loyalty to when we say the Pledge of Allegiance? ",
  answer:"the United States, the flag"},
  {question: "What is one promise you make when you become a United States citizen?",
  answer:"obey the laws of the United States"},
  {question: "How old do citizens have to be to vote for President?*",
  answer:"eighteen (18) and older"},
  {question: "What are two ways that Americans can participate in their democracy?",
  answer:"Vote, join a civic group"},
  {question: "When is the last day you can send in federal income tax forms? *",
  answer:"April 15"},
  {question: "When must all men register for the Selective Service?",
  answer:"between eighteen (18) and twenty-six (26)"},
  {question: "What is one reason colonists came to America?",
  answer:"Freedom"},
  {question: "Who lived in America before the Europeans arrived?",
  answer:"Native Americans"},
  {question: "What group of people was taken to America and sold as slaves?",
  answer:"Africans"},
  {question: "Why did the colonists fight the British?",
  answer:"because of high taxes (taxation without representation)"},
  {question: "Who wrote the Declaration of Independence?",
  answer:"(Thomas) Jefferson"},
  {question: "When was the Declaration of Independence adopted?",
  answer:"July 4, 1776"},
  {question: "There were 13 original states. Name three.",
  answer:"New Hampshire, New York, New Jersey"},
  {question: "What happened at the Constitutional Convention?",
  answer:"The Constitution was written."},
  {question: "When was the Constitution written?",
  answer:"1787"},
  {question: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
  answer:"(James) Madison"},
  {question: "What is one thing Benjamin Franklin is famous for?",
  answer:"U.S. diplomat"},
  {question: "Who is the “Father of Our Country”?",
  answer:"(George) Washington"},
  {question: "Who was the first President?*",
  answer:"(George) Washington"},
  {question: " What territory did the United States buy from France in 1803?",
  answer:"Louisiana"},
  {question: "Name one war fought by the United States in the 1800s.",
  answer:"The Civil War"},
  {question: "Name the U.S. war between the North and the South",
  answer:"The Civil War"},
  {question: "Name one problem that led to the Civil War.",
  answer:"Slavery"},
  {question: "What was one important thing that Abraham Lincoln did?",
  answer:"freed the slaves (Emancipation Proclamation)"},
  {question: "What did the Emancipation Proclamation do?",
  answer:"freed the slaves"},
  {question: "What did Susan B. Anthony do?",
  answer:"fought for women’s rights"},
  {question: "Name one war fought by the United States in the 1900s.*",
  answer:"World War I"},
  {question: "Who was President during World War I?",
  answer:"(Woodrow) Wilson"},
  {question: "Who was President during the Great Depression and World War II?",
  answer:"(Franklin) Roosevelt"},
  {question: "Who did the United States fight in World War II?",
  answer:"Japan, Germany, and Italy"},
  {question: "Before he was President, Eisenhower was a general. What war was he in?",
  answer:"World War II"},
  {question: "During the Cold War, what was the main concern of the United States?",
  answer:"Communism"},
  {question: "What movement tried to end racial discrimination? ",
  answer:"Civil Rights(Movement)"},
  {question: "What did Martin Luther King, Jr. do?*",
  answer:"fought for civil rights"},
  {question: "What major event happened on September 11, 2001, in the United States?",
  answer:"Terrorists attacked the United States."},
  {question: "Name one American Indian tribe in the United States.",
  answer:"Navajo"},
  {question: "Name one of the two longest rivers in the United States.",
  answer:"Mississippi (River)"},
  {question: "What ocean is on the West Coast of the United States?",
  answer:"Pacific (Ocean)"},
  {question: "What ocean is on the East Coast of the United States?",
  answer:"Atlantic (Ocean)"},
  {question: "Name one U.S. territory.",
  answer:"Guam"},
  {question: "Name one state that borders Canada.",
  answer:"New York, Alaska"},
  {question: "Name one state that borders Mexico.",
  answer:"California"},
  {question: "What is the capital of the United States?*",
  answer:"Washington, D.C."},
  {question: "Where is the Statue of Liberty?*",
  answer:"New York (Harbor)"},
  {question: "Why does the flag have 13 stripes? ",
  answer:"because there were 13 original colonies"},
  {question: "Why does the flag have 50 stars?*",
  answer:"because there are 50 states"},
  {question: "What is the name of the national anthem?",
  answer:"The Star-Spangled Banner"},
  {question: "When do we celebrate Independence Day?*",
  answer:"July 4"},
  {question: "Name two national U.S. holidays.",
  answer:"Thanksgiving, Christmas"},
]
const random = Math.floor(Math.random()* questions.length)
const start = document.querySelector(".start")
const question = document.querySelector(".question")
const answer = document.querySelector(".answer")
const show = document.querySelector(".show")
const next = document.querySelector(".next")
const start__Disappear = document.querySelector(".start__disappear h1")

start.addEventListener("click",()=>{
    start.classList.add("hide");
    start__Disappear.classList.add("hide");
    show.classList.remove("hide");
    next.classList.remove("hide");
    removeRandom(questions)
    $(".show").click(function(){
      if($(".answer").hasClass("hide")){
        $(".answer").removeClass("hide");
      } else{
        $(".answer").addClass("hide")
      }
      })
    })

next.addEventListener('click', function(){
  if(!$(".answer").hasClass("hide")){
    $(".answer").addClass("hide");
  }
  removeRandom(questions)
})

const removeRandom = (array) => {
  if (questions.length == 0){
    question.innerHTML= `<h1>Good Job <br>No More Questions</h1>`
    answer.innerHTML="" 
  };
    const random = Math.floor(Math.random() * array.length);
    question.innerHTML= questions[random]["question"];
    answer.innerHTML= questions[random]["answer"];
    const el = array.splice(random, 1);
    console.log(el);

  }

